apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gas-station.fullname" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gas-station.selectorLabels" . | nindent 6 }}
      app: frontend
  template:
    metadata:
      labels:
        {{- include "gas-station.selectorLabels" . | nindent 8 }}
        app: frontend
    spec:
      containers:
        - name: {{ .Chart.Name }}-frontend
          image: "{{ .Values.frontend.repository }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_SOCKET_SERVER_URL
              value: {{ .Values.frontend.socketServerUrl }}
