apiVersion: v1
kind: Service
metadata:
  name: {{ include "gas-station.fullname" . }}-frontend
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "gas-station.selectorLabels" . | nindent 4 }}
    app: frontend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gas-station.fullname" . }}-backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "gas-station.selectorLabels" . | nindent 4 }}
    app: backend