name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      # - name: Git config user
      #   uses: snow-actions/git-config-user@v1.0.0
      #   with:
      #     name: # Service Account's Name
      #     email: # Service Account's Email Address
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Verify Change Logs
        run: node common/scripts/install-run-rush.js change --verify
      - name: Rush Install
        run: node common/scripts/install-run-rush.js install
      - name: Rush rebuild
        run: node common/scripts/install-run-rush.js rebuild --production --verbose

      - name: Extract version or set default
        id: get_version
        shell: bash
        run: |
          VERSION=$(git describe --tags --abbrev=0 --always)
          if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+-(alpha|beta) ]]; then
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/frontend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gas-station-simulator-frontend:${{ steps.get_version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
  
      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./packages/backend
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/gas-station-simulator-backend:${{ steps.get_version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
